[package]
name = "clara"
version = "0.1.0"
edition = "2021"

[dependencies]
codespan-reporting = "0.11.1"
clap = { version = "3.1.18", features = ["derive"] }
serde_json = "1.0.81"
llvm-sys = "130"
eyre = "0.6.8"
