name: Tests
on:
  push:
    branches: [main]
  pull_request:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache LLVM
        uses: actions/cache@v2
        with:
          path: |
            ./llvm
          key: llvm-13.0
      - name: Install LLVM
        uses: KyleMayes/install-llvm-action@v1
        with:
          version: "13.0"
          cached: ${{ steps.cache-llvm.outputs.cache-hit }}
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
      - name: Test on code examples
        run: ./test_examples.sh
